version: "3"
services:
  postgres:
    image: postgres:11.5
    ports:
      - 54328:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: libra_dev
